language: ruby

rvm:
  - "1.9.2" 
  - "1.9.3"
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-19mode
  - 2.0.0
  # - jruby-18mode # JRuby in 1.8 mode
  # - rbx-18mode
  # - "1.8.7"

# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec

matrix:
  allow_failures:
    - rvm: 2.0.0
    - rvm: jruby-19mode
    - rvm: rbx-19mode
